### ISSUE TITLE
LIKE does not seem to be supported anymore

### ISSUE THREAD

**Issue by Toflar** [terminal42/webling-api#2]
Although not documented in http://demo.webling.ch/api/1/#header-changelog it seems like the `LIKE` operator is not supported anymore :(
See http://demo.webling.ch/api/1/#header-operators

**Comment by demianh** [comment]
Webling dev here. We are sorry about the changelog not beeing clearly about that. LIKE has been removed in favour of FILTER (but not with exactly the same behaviour). We might bring back the LIKE operator in the future, but there are some performance considerations we need to sort out first.
For now, please use FILTER.

**Comment by aschempp** [comment]
Updated in d99f9bf58af111d84688a81b8d4699dadd9e3e37
